
> library(syuzhet)
> x<-read.csv2("C:\Users\NICK-TECH\Documents\code_SN\code_SN.Rproj")
Error: '\U' used without hex digits in character string (<input>:1:18)
> x<-read.csv2("C:\Users\NICK-TECH\Documents\dossier_code_sn\data.csv")
Error: '\U' used without hex digits in character string (<input>:1:18)
> x<-read.csv2("C:/Users/NICK-TECH/Documents/dossier_code_sn/data.csv")
> viwe(x)
Error in viwe(x) : could not find function "viwe"
> View(x)
> mean(satisfaction)
Error: object 'satisfaction' not found
> y<-read.csv2("C:\Users\NICK-TECH\Documents\dossier_code_sn\dataset-csv_service_data.csv")
Error: '\U' used without hex digits in character string (<input>:1:18)
> y<-read.csv2("C:/Users/NICK-TECH/Documents/dossier_code_sn/dataset-csv_service_data.csv")
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
                      duplicate 'row.names' are not allowed
                    In addition: Warning message:
                      In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                EOF within quoted string
                              > y<-read.csv2("C:/Users/NICK-TECH/Documents/dossier_code_sn/dataset-csv_service_data.csv")
                              Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
                                                    duplicate 'row.names' are not allowed
                                                  In addition: Warning message:
                                                    In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                              EOF within quoted string
                                                            > y<-read.csv2("C:\Users\NICK-TECH\Documents\dossier_code_sn\dataset.csv")
                                                            Error: '\U' used without hex digits in character string (<input>:1:18)
                                                            > y<-read.csv2("C:/Users/NICK-TECH/Documents/dossier_code_sn/dataset.csv")
                                                            Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
                                                                                  duplicate 'row.names' are not allowed
                                                                                In addition: Warning message:
                                                                                  In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                                                            EOF within quoted string
                                                                                          > mean(.satisfaction)
                                                                                          Error: object '.satisfaction' not found
                                                                                          > mean(x$employee_id.productivity.satisfaction)
                                                                                          [1] NA
                                                                                          Warning message:
                                                                                            In mean.default(x$employee_id.productivity.satisfaction) :
                                                                                            argument is not numeric or logical: returning NA
                                                                                          > mean(x$employee_id.productivity.satisfaction na.rm=TRUE)
                                                                                          Error: unexpected symbol in "mean(x$employee_id.productivity.satisfaction na.rm"
                                                                                          > y<-read.csv2("C:/Users/NICK-TECH/Documents/dossier_code_sn/dataset.csv")
                                                                                          Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
                                                                                                                duplicate 'row.names' are not allowed
                                                                                                              In addition: Warning message:
                                                                                                                In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                                                                                          EOF within quoted string
                                                                                                                        > View(x)
                                                                                                                        > y<-read.csv2("C:\Users\NICK-TECH\Documents\dossier_code_sn\donnees.csv")
                                                                                                                        Error: '\U' used without hex digits in character string (<input>:1:18)
                                                                                                                        > y<-read.csv2("C:/Users/NICK-TECH/Documents/dossier_code_sn/donnees.csv")
                                                                                                                        Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
                                                                                                                                              duplicate 'row.names' are not allowed
                                                                                                                                            In addition: Warning message:
                                                                                                                                              In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                                                                                                                        EOF within quoted string
                                                                                                                                                      > y<-read.csv2("C:\Users\NICK-TECH\Documents\code_SN\donnees.csv")
                                                                                                                                                      Error: '\U' used without hex digits in character string (<input>:1:18)
                                                                                                                                                      > y<-read.csv2("C:/Users/NICK-TECH/Documents/code_SN/donnees.csv")
                                                                                                                                                      Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
                                                                                                                                                                            duplicate 'row.names' are not allowed
                                                                                                                                                                          In addition: Warning message:
                                                                                                                                                                            In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                                                                                                                                                      EOF within quoted string
                                                                                                                                                                                    > moy<-mean(x$employee_id.productivity.satisfaction)
                                                                                                                                                                                    Warning message:
                                                                                                                                                                                      In mean.default(x$employee_id.productivity.satisfaction) :
                                                                                                                                                                                      argument is not numeric or logical: returning NA
                                                                                                                                                                                    > moy<-mean(x$.satisfaction)
                                                                                                                                                                                    Warning message:
                                                                                                                                                                                      In mean.default(x$.satisfaction) :
                                                                                                                                                                                      argument is not numeric or logical: returning NA
                                                                                                                                                                                    > moy<-mean(x$satisfaction na.rm=TRUE)
                                                                                                                                                                                    Error: unexpected symbol in "moy<-mean(x$satisfaction na.rm"
                                                                                                                                                                                    > moy<-mean(x$satisfaction na.rm="TRUE")
                                                                                                                                                                                    Error: unexpected symbol in "moy<-mean(x$satisfaction na.rm"
                                                                                                                                                                                    > ecart_type<-sd(x$employee_id.productivity.satisfaction)
                                                                                                                                                                                    Warning message:
                                                                                                                                                                                      In var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm) :
                                                                                                                                                                                      NAs introduced by coercion
                                                                                                                                                                                    > ecart_type<-sd(x$employee_id.productivity.satisfaction where na.rm = TRUE)
                                                                                                                                                                                    Error: unexpected symbol in "ecart_type<-sd(x$employee_id.productivity.satisfaction where"
                                                                                                                                                                                    > y<-read.csv2("C:/Users/NICK-TECH/Documents/code_SN/donnees.csv")
                                                                                                                                                                                    Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
                                                                                                                                                                                                          duplicate 'row.names' are not allowed
                                                                                                                                                                                                        In addition: Warning message:
                                                                                                                                                                                                          In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                                                                                                                                                                                    EOF within quoted string
                                                                                                                                                                                                                  > y<read.csv("C:\Users\NICK-TECH\Documents\code_SN\donnees.csv")
                                                                                                                                                                                                                  Error: '\U' used without hex digits in character string (<input>:1:16)
                                                                                                                                                                                                                  > y<read.csv("C:/Users/NICK-TECH/Documents/code_SN/donnees.csv")
                                                                                                                                                                                                                  Error: object 'y' not found
                                                                                                                                                                                                                  > y<-read.csv("C:/Users/NICK-TECH/Documents/code_SN/donnees.csv")
                                                                                                                                                                                                                  Warning message:
                                                                                                                                                                                                                    In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                                                                                                                                                                                              EOF within quoted string
                                                                                                                                                                                                                            > View(y)
                                                                                                                                                                                                                            > med<-median(x$employee_id.productivity.satisfaction where na.rm = TRUE)
                                                                                                                                                                                                                            Error: unexpected symbol in "med<-median(x$employee_id.productivity.satisfaction where"
                                                                                                                                                                                                                            > med<-median(x$employee_id.productivity.satisfaction  na.rm = TRUE)
                                                                                                                                                                                                                            Error: unexpected symbol in "med<-median(x$employee_id.productivity.satisfaction  na.rm"
                                                                                                                                                                                                                            > #histogramme de satisfaction des employes
                                                                                                                                                                                                                              > 
                                                                                                                                                                                                                              > ggplot(x, aes(x=satisfaction)) +
                                                                                                                                                                                                                              +     geom_histogram(binwidth=1, fill="blue", color="black", alpha=0.7) +
                                                                                                                                                                                                                              +     labs(title="Répartition de la satisfaction des employés",
                                                                                                                                                                                                                                         +          x="Niveau de satisfaction",
                                                                                                                                                                                                                                         +          y="Nombre d'employés")
                                                                                                                                                                                                                            Error in ggplot(x, aes(x = satisfaction)) : 
                                                                                                                                                                                                                              could not find function "ggplot"
                                                                                                                                                                                                                            > View(x)
                                                                                                                                                                                                                            > View(y)
                                                                                                                                                                                                                            > library(ggplot2)
                                                                                                                                                                                                                            > install.packages("ggplot")
                                                                                                                                                                                                                            WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
                                                                                                                                                                                                                              
                                                                                                                                                                                                                              https://cran.rstudio.com/bin/windows/Rtools/
                                                                                                                                                                                                                              Installing package into ‘C:/Users/NICK-TECH/AppData/Local/R/win-library/4.3’
                                                                                                                                                                                                                            (as ‘lib’ is unspecified)
                                                                                                                                                                                                                            Warning in install.packages :
                                                                                                                                                                                                                              package ‘ggplot’ is not available for this version of R
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            A version of this package for your version of R might be available elsewhere,
                                                                                                                                                                                                                            see the ideas at
                                                                                                                                                                                                                            https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
                                                                                                                                                                                                                            > 
                                                                                                                                                                                                                              
                                                                                                                                                                                                                              Restarting R session...
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            > install.packages("ggplot2")
                                                                                                                                                                                                                            WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
                                                                                                                                                                                                                              
                                                                                                                                                                                                                              https://cran.rstudio.com/bin/windows/Rtools/
                                                                                                                                                                                                                              Installing package into ‘C:/Users/NICK-TECH/AppData/Local/R/win-library/4.3’
                                                                                                                                                                                                                            (as ‘lib’ is unspecified)
                                                                                                                                                                                                                            trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/ggplot2_3.5.1.zip'
                                                                                                                                                                                                                            Content type 'application/zip' length 4962192 bytes (4.7 MB)
                                                                                                                                                                                                                            downloaded 4.7 MB
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            package ‘ggplot2’ successfully unpacked and MD5 sums checked
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            The downloaded binary packages are in
                                                                                                                                                                                                                            C:\Users\NICK-TECH\AppData\Local\Temp\RtmpSAMcrS\downloaded_packages
                                                                                                                                                                                                                            > ggplot2(x, aes(x=factor(satisfaction), y=productivite)) +
                                                                                                                                                                                                                              +     geom_boxplot(fill="cyan", color="black") +
                                                                                                                                                                                                                              +     labs(title="Comparaison de la productivité selon la satisfaction",
                                                                                                                                                                                                                                         +          x="Satisfaction des employés",
                                                                                                                                                                                                                                         +          y="Productivité") +
                                                                                                                                                                                                                              +     theme_minimal()
                                                                                                                                                                                                                            Error in ggplot2(x, aes(x = factor(satisfaction), y = productivite)) : 
                                                                                                                                                                                                                              could not find function "ggplot2"
                                                                                                                                                                                                                            > ggplot(x, aes(x=factor(satisfaction), y=productivite)) +
                                                                                                                                                                                                                              +     geom_boxplot(fill="cyan", color="black") +
                                                                                                                                                                                                                              +     labs(title="Comparaison de la productivité selon la satisfaction",
                                                                                                                                                                                                                                         +          x="Satisfaction des employés",
                                                                                                                                                                                                                                         +          y="Productivité") +
                                                                                                                                                                                                                              +     theme_minimal()
                                                                                                                                                                                                                            Error in ggplot(x, aes(x = factor(satisfaction), y = productivite)) : 
                                                                                                                                                                                                                              could not find function "ggplot"
                                                                                                                                                                                                                            > install.packages("syuzhet")
                                                                                                                                                                                                                            WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:
                                                                                                                                                                                                                              
                                                                                                                                                                                                                              https://cran.rstudio.com/bin/windows/Rtools/
                                                                                                                                                                                                                              Installing package into ‘C:/Users/NICK-TECH/AppData/Local/R/win-library/4.3’
                                                                                                                                                                                                                            (as ‘lib’ is unspecified)
                                                                                                                                                                                                                            trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/syuzhet_1.0.7.zip'
                                                                                                                                                                                                                            Content type 'application/zip' length 3110023 bytes (3.0 MB)
                                                                                                                                                                                                                            downloaded 3.0 MB
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            package ‘syuzhet’ successfully unpacked and MD5 sums checked
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            The downloaded binary packages are in
                                                                                                                                                                                                                            C:\Users\NICK-TECH\AppData\Local\Temp\RtmpSAMcrS\downloaded_packages
                                                                                                                                                                                                                            > ggplot(x, aes(x=factor(satisfaction), y=productivite)) +
                                                                                                                                                                                                                              +     geom_boxplot(fill="cyan", color="black") +
                                                                                                                                                                                                                              +     labs(title="Comparaison de la productivité selon la satisfaction",
                                                                                                                                                                                                                                         +          x="Satisfaction des employés",
                                                                                                                                                                                                                                         +          y="Productivité") +
                                                                                                                                                                                                                              +     theme_minimal()
                                                                                                                                                                                                                            Error in ggplot(x, aes(x = factor(satisfaction), y = productivite)) : 
                                                                                                                                                                                                                              could not find function "ggplot"
                                                                                                                                                                                                                            > hist<-hist(x$satisfaction,x$productivite)
                                                                                                                                                                                                                            Error in hist.default(x$satisfaction, x$productivite) : 
                                                                                                                                                                                                                              'x' must be numeric
                                                                                                                                                                                                                            > show(x)
                                                                                                                                                                                                                            employee_id.productivity.satisfaction
                                                                                                                                                                                                                            1                                 1,40,8
                                                                                                                                                                                                                            2                                 2,35,7
                                                                                                                                                                                                                            3                                 3,45,9
                                                                                                                                                                                                                            4                                4,50,10
                                                                                                                                                                                                                            5                                 5,38,6
                                                                                                                                                                                                                            6                                 6,42,8
                                                                                                                                                                                                                            7                                 7,48,9
                                                                                                                                                                                                                            8                                 8,37,6
                                                                                                                                                                                                                            9                                 9,41,7
                                                                                                                                                                                                                            10                               10,43,8
                                                                                                                                                                                                                            11                               11,39,7
                                                                                                                                                                                                                            12                               12,36,5
                                                                                                                                                                                                                            13                               13,47,9
                                                                                                                                                                                                                            14                              14,49,10
                                                                                                                                                                                                                            15                               15,46,9
                                                                                                                                                                                                                            16                               16,34,5
                                                                                                                                                                                                                            17                               17,33,4
                                                                                                                                                                                                                            18                               18,44,8
                                                                                                                                                                                                                            19                              19,51,10
                                                                                                                                                                                                                            20                              20,52,10
                                                                                                                                                                                                                            > head(x)
                                                                                                                                                                                                                            employee_id.productivity.satisfaction
                                                                                                                                                                                                                            1                                1,40,8
                                                                                                                                                                                                                            2                                2,35,7
                                                                                                                                                                                                                            3                                3,45,9
                                                                                                                                                                                                                            4                               4,50,10
                                                                                                                                                                                                                            5                                5,38,6
                                                                                                                                                                                                                            6                                6,42,8
                                                                                                                                                                                                                            > #test de correlation
                                                                                                                                                                                                                              > correlation_result <- cor.test(data$satisfaction, data$productivite, method="pearson")
                                                                                                                                                                                                                            Error in data$satisfaction : object of type 'closure' is not subsettable
                                                                                                                                                                                                                            > correlation_result <- cor.test(data$satisfaction, data$productivite, method="pearson")
                                                                                                                                                                                                                            Error in data$satisfaction : object of type 'closure' is not subsettable
                                                                                                                                                                                                                            > 
                                                                                                                                                                                                                              > correlation_result <- cor.test(data$satisfaction, data$productivite)
                                                                                                                                                                                                                            Error in data$satisfaction : object of type 'closure' is not subsettable
                                                                                                                                                                                                                            > z<-read.csv2("C:\Users\NICK-TECH\Documents\dossier_code_sn\comments.htm")
                                                                                                                                                                                                                            Error: '\U' used without hex digits in character string (<input>:1:18)
                                                                                                                                                                                                                            > z<-read.csv2("C:/Users/NICK-TECH/Documents/dossier_code_sn/comments.htm")
                                                                                                                                                                                                                            Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
                                                                                                                                                                                                                                                  duplicate 'row.names' are not allowed
                                                                                                                                                                                                                                                In addition: Warning message:
                                                                                                                                                                                                                                                  In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                                                                                                                                                                                                                            EOF within quoted string
                                                                                                                                                                                                                                                          > z<-read.csv("C:/Users/NICK-TECH/Documents/dossier_code_sn/comments.htm")
                                                                                                                                                                                                                                                          Warning message:
                                                                                                                                                                                                                                                            In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
                                                                                                                                                                                                                                                                      EOF within quoted string
                                                                                                                                                                                                                                                                    > View(z)
                                                                                                                                                                                                                                                                    > analyse<-(z$sentiments)
                                                                                                                                                                                                                                                                    > library(syuzhet)
                                                                                                                                                                                                                                                                    > analyse<-(z$sentiments)
                                                                                                                                                                                                                                                                    > sentiments<-get_nrc_sentiment(z$X..DOCTYPE.html.)
                                                                                                                                                                                                                                                                    > z<-colSums(sentiments)
                                                                                                                                                                                                                                                                    > #visualiser les resultats
                                                                                                                                                                                                                                                                      > z<-colSums(sentiments)
                                                                                                                                                                                                                                                                    > #interpreter les resultats
                                                                                                                                                                                                                                                                      > total_positif <- sentiment_summary["positive"]
                                                                                                                                                                                                                                                                    Error: object 'sentiment_summary' not found
                                                                                                                                                                                                                                                                    > total_positif <- z["positive"]
                                                                                                                                                                                                                                                                    > total_negatif <- z["negative"]
                                                                                                                                                                                                                                                                    > total_joie <- z["joy"]
                                                                                                                                                                                                                                                                    > total_colere <- z["anger"]